# Generated by Django 2.0.5 on 2018-06-04 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publishDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
