# Generated by Django 2.0.7 on 2018-08-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalDescription', models.TextField(null=True)),
                ('personalImg', models.CharField(max_length=300, null=True)),
                ('hobbyDescription', models.TextField(null=True)),
                ('hobbyImg', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField(null=True)),
                ('author', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, null=True)),
                ('startDate', models.IntegerField(null=True)),
                ('endDate', models.IntegerField(null=True)),
                ('institution', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=225, null=True)),
                ('photo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, null=True)),
                ('startDate', models.IntegerField(null=True)),
                ('endDate', models.IntegerField(null=True)),
                ('institution', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='publishDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=225),
        ),
        migrations.AddField(
            model_name='projectimgs',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Project'),
        ),
    ]
