# Generated by Django 2.0.6 on 2018-06-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_blog_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
