# Generated by Django 2.0.6 on 2018-06-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20180625_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='humbnail_url',
            field=models.TextField(null=True),
        ),
    ]
