# Generated by Django 2.0.6 on 2018-06-28 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20180625_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Project')),
            ],
        ),
    ]
