# Generated by Django 2.0.7 on 2018-08-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20180717_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, null=True)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('institution', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hobbies',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='hobbyDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='hobbyImg',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='personalDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='personalImg',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectimgs',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Project'),
        ),
    ]
