# Generated by Django 2.0.7 on 2018-08-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_auto_20180824_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='endDate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='startDate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projectimgs',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Project'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='endDate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='startDate',
            field=models.IntegerField(null=True),
        ),
    ]
